const $=id=>document.getElementById(id);let S=null,token=sessionStorage.getItem('djibabouya-token')||'',ws=null,clockTimer=null;
const api=async(path,opt={})=>{const r=await fetch(path,{cache:'no-store',...opt,headers:{...(opt.headers||{}),'x-admin-token':token}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur réseau');return d};
const deep=x=>JSON.parse(JSON.stringify(x));
async function boot(){S=await api('/api/state');render();connectWS();setInterval(refreshLive,10000);refreshLive()}
function connectWS(){if(ws){ws.close()}const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/ws`);$('connection').textContent='● Temps réel…';ws.onopen=()=>$('connection').textContent='● Synchronisé en temps réel';ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='state'){S=d.state;render()}}catch{}};ws.onclose=()=>{$('connection').textContent='● Reconnexion…';setTimeout(connectWS,1200)};ws.onerror=()=>ws.close()}
async function publish(mutator){if(!token)throw new Error('Connectez-vous à l’Admin.');const n=deep(S);await mutator(n);const d=await api('/api/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state:n})});S=d.state;render()}
function elapsed(){if(!S)return 0;let x=Number(S.elapsed)||0;if(S.running&&S.startedAt)x+=(Date.now()-S.startedAt)/1000;return Math.floor(x)}
function extraElapsed(){let x=Number(S.extraElapsed)||0;if(S.extraRunning&&S.extraStartedAt)x+=(Date.now()-S.extraStartedAt)/1000;return Math.floor(x)}
const fmt=x=>`${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`;
function timed(obj,key){if(!obj.visible||!obj.startedAt||!obj.duration)return obj.visible;return Date.now()-obj.startedAt<obj.duration*1000}
function render(){if(!S)return;const bg=$('bg');bg.style.backgroundImage=`url("${S.background||'/default-background.jpg'}")`;bg.style.backgroundSize=S.backgroundMode||'cover';
 $('homeName').textContent=S.home.name;$('awayName').textContent=S.away.name;$('score').textContent=`${S.home.score} - ${S.away.score}`;$('homeBox').style.background=S.home.color;$('awayBox').style.background=S.away.color;$('homeBox').style.color=S.home.text;$('awayBox').style.color=S.away.text;
 for(const [id,url] of [['homeLogo',S.home.logo],['awayLogo',S.away.logo]]){const e=$(id);e.src=url||'';e.style.display=url?'block':'none'}
 $('scoreboard').hidden=!S.scoreboardVisible;$('clock').textContent=fmt(elapsed());$('extra').textContent=S.extraMinutes?`+${S.extraMinutes}`:'';
 $('ticker').hidden=!S.messageVisible;$('ticker').textContent=S.message||'';
 const a=S.ad,showAd=timed(a,'ad');$('adOverlay').hidden=!showAd;$('adImage').hidden=true;$('adVideo').hidden=true;$('adTitle').textContent=a.title||'';$('adText').textContent=a.text||'';if(a.kind==='image'&&a.image){$('adImage').src=a.image;$('adImage').hidden=false}if(a.kind==='video'&&a.video){const v=$('adVideo');if(v.src!==location.origin+a.video)v.src=a.video;v.hidden=false}
 const r=S.replay,showReplay=timed(r,'replay');$('replayOverlay').hidden=!showReplay;if(showReplay&&r.url){const v=$('replayVideo');if(v.src!==r.url){v.src=r.url;v.playbackRate=r.speed||1;v.play().catch(()=>{})}}
 const sub=S.substitution,showSub=timed(sub,'substitution');$('subOverlay').hidden=!showSub;[['subOutPhoto',sub.out.photo],['subInPhoto',sub.in.photo]].forEach(([id,u])=>$(id).src=u||'');$('subOutName').textContent=sub.out.name||'';$('subOutNumber').textContent=sub.out.number||'';$('subInName').textContent=sub.in.name||'';$('subInNumber').textContent=sub.in.number||'';
 $('lineupOverlay').hidden=!S.lineup.visible;$('lineupTitle').textContent=`COMPOSITION — ${S.lineup.team==='home'?S.home.name:S.away.name} (${S.lineup.formation})`;$('pitch').innerHTML=S.lineup.players.map(x=>`<div class="player">${escapeHtml(typeof x==='string'?x:x.name||'Joueur')}</div>`).join('');
 $('posterOverlay').hidden=!S.poster.visible;$('posterImage').src=S.poster.image||'';$('varOverlay').hidden=!S.var.visible;$('varTitle').textContent=S.var.title||'VAR';$('varText').textContent=S.var.text||'';$('penaltyOverlay').hidden=!S.penalty.visible;$('penaltyScore').textContent=`${S.penalty.home||0} - ${S.penalty.away||0}`;
 clearInterval(clockTimer);clockTimer=setInterval(()=>{$('clock').textContent=fmt(elapsed());$('extra').textContent=S.extraMinutes?`+${S.extraMinutes}`:'';if(!S.ad.visible||timed(S.ad)){}renderTimed()},1000)
}
function renderTimed(){if(!S)return;$('adOverlay').hidden=!timed(S.ad,'ad');$('replayOverlay').hidden=!timed(S.replay,'replay');$('subOverlay').hidden=!timed(S.substitution,'substitution')}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function upload(file){if(!file)return '';const fd=new FormData();fd.append('file',file);const d=await api('/api/media',{method:'POST',body:fd});return d.url}
function adminOpen(){if(token)$('admin').showModal();else $('login').showModal()}
$('adminButton').onclick=adminOpen;$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{const d=await api('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:$('password').value})});token=d.token;sessionStorage.setItem('djibabouya-token',token);$('login').close();$('admin').showModal()}catch(e){$('loginError').textContent=e.message}});$('closeAdmin').onclick=()=>$('admin').close();
$('saveTeams').onclick=()=>publish(s=>{s.home.name=$('homeInput').value||'A';s.away.name=$('awayInput').value||'B';s.status=$('statusInput').value});
$('homePlus').onclick=()=>publish(s=>s.home.score++);$('homeMinus').onclick=()=>publish(s=>s.home.score=Math.max(0,s.home.score-1));$('awayPlus').onclick=()=>publish(s=>s.away.score++);$('awayMinus').onclick=()=>publish(s=>s.away.score=Math.max(0,s.away.score-1));
$('startClock').onclick=()=>publish(s=>{if(!s.running){s.running=true;s.startedAt=Date.now()}});$('stopClock').onclick=()=>publish(s=>{if(s.running){s.elapsed+=Math.floor((Date.now()-s.startedAt)/1000);s.running=false;s.startedAt=0}});$('resetClock').onclick=()=>publish(s=>{s.elapsed=0;s.startedAt=0;s.running=false;s.extraElapsed=0;s.extraRunning=false});$('saveExtra').onclick=()=>publish(s=>s.extraMinutes=Number($('extraInput').value)||0);$('scoreVisible').onchange=e=>publish(s=>s.scoreboardVisible=e.target.checked);
function eventData(){return {player:$('eventPlayer').value,minute:Number($('eventMinute').value)||0,team:$('eventTeam').value,createdAt:Date.now(),id:crypto.randomUUID()}}
$('goalBtn').onclick=()=>publish(s=>{const g=eventData();s.goals.push(g);s.events.push({...g,type:'goal'});s[g.team].score++});document.querySelectorAll('.cardBtn').forEach(b=>b.onclick=()=>publish(s=>{const e=eventData();s.cards.push({...e,type:b.dataset.card});s.events.push({...e,type:b.dataset.card})}));$('halfBtn').onclick=()=>publish(s=>{s.status='MI-TEMPS';s.running=false;s.period='MI-TEMPS'});$('fullBtn').onclick=()=>publish(s=>{s.status='TERMINÉ';s.running=false;s.period='FIN'});$('varBtn').onclick=()=>publish(s=>{s.var.visible=!s.var.visible;s.var.title='VAR';s.var.text=s.var.visible?'DÉCISION EN COURS':'';s.var.publicationId=crypto.randomUUID()});
$('saveStats').onclick=()=>publish(s=>{s.stats.possessionHome=Number($('posH').value)||0;s.stats.possessionAway=Number($('posA').value)||0;s.stats.shotsHome=Number($('shotsH').value)||0;s.stats.shotsAway=Number($('shotsA').value)||0;s.stats.cornersHome=Number($('cornersH').value)||0;s.stats.cornersAway=Number($('cornersA').value)||0});
$('publishMessage').onclick=()=>publish(s=>{s.message=$('messageInput').value;s.messageVisible=true});$('removeMessage').onclick=()=>publish(s=>{s.message='';s.messageVisible=false});
$('publishAd').onclick=async()=>{try{const f=$('adFile').files[0],url=f?await upload(f):'';await publish(s=>{s.ad={visible:true,kind:f?.type.startsWith('video/')?'video':f?'image':'text',title:$('adTitleInput').value,text:$('adTextInput').value,image:f&&!f.type.startsWith('video/')?url:'',video:f?.type.startsWith('video/')?url:'',startedAt:Date.now(),duration:Number($('adDurationInput').value)||0,publicationId:crypto.randomUUID()}})}catch(e){alert(e.message)}};$('stopAd').onclick=()=>publish(s=>s.ad.visible=false);
async function doReplay(slow){$('replayStatus').textContent='Création du clip…';try{const d=await api('/api/live/replay',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({before:$('replayBefore').value,after:$('replayAfter').value})});await publish(s=>s.replay={visible:true,url:d.url,startedAt:Date.now(),duration:d.duration*(slow?1/(Number($('replaySpeed').value)||.5):1),speed:slow?Number($('replaySpeed').value)||.5:1,publicationId:crypto.randomUUID()});$('replayStatus').textContent='✓ Replay publié instantanément'}catch(e){$('replayStatus').textContent='✕ '+e.message}}$('liveReplay').onclick=()=>doReplay(false);$('liveSlow').onclick=()=>doReplay(true);$('stopReplay').onclick=()=>publish(s=>s.replay.visible=false);
$('publishSub').onclick=async()=>{try{const out=await upload($('subOutFile').files[0]),inn=await upload($('subInFile').files[0]);await publish(s=>s.substitution={visible:true,out:{name:$('subOutName').value,number:$('subOutNumber').value,photo:out},in:{name:$('subInName').value,number:$('subInNumber').value,photo:inn},startedAt:Date.now(),duration:12,publicationId:crypto.randomUUID()})}catch(e){alert(e.message)}};$('stopSub').onclick=()=>publish(s=>s.substitution.visible=false);
$('publishLineup').onclick=()=>publish(s=>{s.lineup={visible:true,team:'home',formation:$('formation').value,players:$('lineupPlayers').value.split('\n').map(x=>x.trim()).filter(Boolean),publicationId:crypto.randomUUID()}});$('stopLineup').onclick=()=>publish(s=>s.lineup.visible=false);
$('publishPoster').onclick=async()=>{try{const u=await upload($('posterFile').files[0]);await publish(s=>s.poster={visible:true,image:u,publicationId:crypto.randomUUID()})}catch(e){alert(e.message)}};$('stopPoster').onclick=()=>publish(s=>s.poster.visible=false);
$('changeBackground').onclick=async()=>{try{const u=await upload($('backgroundFile').files[0]);await publish(s=>{s.background=u;s.backgroundMode=$('backgroundMode').value})}catch(e){alert(e.message)}};$('removeBackground').onclick=()=>publish(s=>{s.background='/default-background.jpg';s.backgroundMode=$('backgroundMode').value});$('backgroundMode').onchange=e=>publish(s=>s.backgroundMode=e.target.value);
$('createLiveInput').onclick=async()=>{try{const d=await api('/api/live/input',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('liveName').value})});$('liveCredentials').textContent=JSON.stringify({uid:d.input.uid,rtmps:d.input.rtmps,srt:d.input.srt,webRTC:d.input.webRTC},null,2)}catch(e){$('liveCredentials').textContent='Erreur: '+e.message}};$('checkLive').onclick=async()=>{try{const d=await api('/api/live/status');$('liveCredentials').textContent=JSON.stringify(d,null,2);if(d.ok){S.live={enabled:true,hls:d.hls,videoId:d.videoId,inputId:d.inputId};render();playLive(d.hls)}}catch(e){$('liveCredentials').textContent='Erreur: '+e.message}};
$('publishPenalty').onclick=()=>publish(s=>{s.penalty={...s.penalty,visible:true,home:Number($('penH').value)||0,away:Number($('penA').value)||0,publicationId:crypto.randomUUID()}});$('stopPenalty').onclick=()=>publish(s=>s.penalty.visible=false);
function playLive(hls){const v=$('liveVideo');if(!hls)return;if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=hls;v.play().catch(()=>{})}else{$('liveHint').innerHTML='DIRECT ACTIF<br><small>Ce navigateur nécessite un lecteur HLS compatible</small>'}}
async function refreshLive(){try{const d=await api('/api/live/status');if(d.ok){playLive(d.hls);$('liveHint').style.display='none'}}catch{}}
boot().catch(e=>{$('connection').textContent='● Erreur de démarrage';console.error(e)});
